### ISSUE TITLE
Inconsistent name in index.theme 

### ISSUE THREAD

**Issue by fmeloni** [LinxGem33/OSX-Arc-Plus#1]
The theme is stored in a folder named OSX-Arc-Plus, but all the references to the theme name, GtkTheme and MetacityTheme in index.theme file are defined as OSX-Arc-White+.

**Comment by LinxGem33** [comment]
@fmeloni 

appreciate the feed back, I know about the issue its because i changed the name just didn't get around to changing the index file etc but it will be fixed very soon :)

kind regards

**Comment by fmeloni** [comment]
Excellent. I have some little things I would like to give you. I tweaked the original Arc gnome-shell theme and forked it in two versions, a dark one and a light one, with a cool rocket launcher icon and also made disappear the three points in the top left corner and reinstated the word "Activities". I called them Arco and Arco-Plus (I followed your naming, heh). I don't have the time to maintain a full theme, but I think you will find them useful. How can I deliver them to you?

**Comment by LinxGem33** [comment]
@fmeloni 

appreciate the feed back, the easiest way would be to upload the theme to your own repo and i could then take a look at it or if your unable to create and upload to a repo Id suggest using dropbox or a service similar.

kind regards

**Comment by fmeloni** [comment]
Cool. I uploaded them to Dropbox. I hope you find them useful.

https://www.dropbox.com/sh/y7xem45y9gahfb5/AAD7Oy1qh6ERLQ6Kg-nLmbPOa?dl=0

**Comment by LinxGem33** [comment]
@fmeloni 

appreciate you taking the time to upload  the shell themes.

kind regards
