### ISSUE TITLE
Maximize button does not show when Chrome is maximized

### ISSUE THREAD

**Issue by Parentheseas** [LinxGem33/OSX-Arc-Plus#15]
Chrome looks great with this theme, no ugly top bar anymore. Although I'm missing the green maximize button only in Chrome and when it is maximized.
Chrome Version 62.0.3202.75 (Official Build) (64-bit)
Latest Arch and Gnome 3.26
![window buttons](https://user-images.githubusercontent.com/20146162/32591668-1b8c6ee8-c4d5-11e7-84a2-689aaaf1e9da.png)
![chrome settings](https://user-images.githubusercontent.com/20146162/32591670-1f46c04c-c4d5-11e7-8a6b-f435a734d28b.png)

Thanks

**Comment by LinxGem33** [comment]
now fixed in chrome 63.

**Comment by LinxGem33** [comment]
#63
