### ISSUE TITLE
AUR package is broken with latest update

### ISSUE THREAD

**Issue by bdbch** [LinxGem33/OSX-Arc-Plus#16]
With the latest version I can't install the themes anymore. I get following error:

> Error: One or more files did not pass the validity check!

**Comment by LinxGem33** [comment]
hi appreciate the feedback i dont maintain the AUR repo 

AUR Note: If you're having trouble with the AUR packages please submit a request to the current package maintainer which is currently maintained by jaxmetalmax.

**Comment by bdbch** [comment]
Ah, sorry for that! Thanks 👍
