### ISSUE TITLE
I would like to contribute 

### ISSUE THREAD

**Issue by paullinuxthemer** [LinxGem33/OSX-Arc-Plus#3]
I'm new at this.  So posting this here is probably not the best place.  Anyway I (paullinuxthemer) (alias PaulXFCE, alias Manjarocinnamonfan) would like to be a fellow developer in some way.

**Comment by LinxGem33** [comment]
@paullinuxthemer 

welcome aboard ill add you now as a contributor to the neon theme its the new theme currently in development there are a few css developers and beta testers like i said who are currently contributing once you have collaborator status you will be able to commit and push code to the repository ie make changes, if your new to contributing on github don’t worry ill guide you through or one of the developers or testers will if I’m unable to reply straight away, once you see that you’ve been added to the developer list on the neon theme head over over to developer discussion and ill guide you further on the project and we can discuss further how you want to contribute just to make you aware developer discussion is locked to just developers. all that’s left to say is i look forward to working with you and welcome aboard.

kind regards
