### ISSUE TITLE
Is this one still being worked on?

### ISSUE THREAD

**Issue by 9Morello** [LinxGem33/OSX-Arc-Plus#4]
Hello! Thanks for this awesome theme pack.
Is this version still being worked on? I've been looking for an Arc variant with a light side panel.

As a suggestion, I think this one will look better using the darker fonts.

Thanks again!

**Comment by LinxGem33** [comment]
@9Morello 

appreciate the feed back, concerning this theme I’ve not forgotten about it, at the moment I’ve just finished a gnome extension and its now live on ![extensions.gnome.org](https://extensions.gnome.org/extension/1190/ip-finder/) I’m also just finishing a icon theme to accompany the OSX-Arc theme collection, once that’s finished ill be finishing updating the theme collection for the upcoming 17.04 release and after that ill continue work on this theme, but your more than welcome to work on this theme in the mean time and push the changes via a pull request and if they work and fit the design profile ill merge the changes.

kind regards
