### ISSUE TITLE
Nautilus location and search input customization

### ISSUE THREAD

**Issue by mmatsumoto** [LinxGem33/OSX-Arc-Plus#9]
Hi, 

first of all, great job on this theme. Really nice work.

I'm not sure if this is the right place to ask this because this is not a "issue", but I'm playing around with this theme for the last hours and I couldn't figure out few things. Maybe you can help me.

How I can make all "input texts" rounded? Special on Nautilus and Gedit when you press CTRL+L or CTRL+F

I successful changed few places like on gnome-shell .search-entry  but no luck with Nautilus and Gedit so far.

I'm digging the internet looking for some guide and documentation about Themes but everything looks so vague.
E.g. [https://developer.gnome.org/gtk3/stable/chap-css-overview.html](url)

Again, thanks for theme!

**Comment by LinxGem33** [comment]
@mmatsumoto 

for [nautilus](https://github.com/LinxGem33/OSX-Arc-Plus/blob/master/gtk-3.0/gtk.css#L3694) you will also see gedit also start from line 3694 down.

kind regards
